<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-42ALJV1" name="com.runnerclass.TestRunnerClass" tests="1" failures="1" timestamp="25 Aug 2019 10:27:55 GMT" time="43.854" errors="0">
  <testcase name="feature" time="43.854" classname="com.runnerclass.TestRunnerClass">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: The following asserts failed:
expected [404] but found [200]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: The following asserts failed:
expected [404] but found [200]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: The following asserts failed:
expected [404] but found [200]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at com.pageobject.RestCRUDPageObject.performDeleteForInvalidEmp(RestCRUDPageObject.java:385)
	at com.stepdefn.RestCrudStepdefinition.Peform_Delete_operation_for_invalid_employee(RestCrudStepdefinition.java:169)
	at âœ½.And Peform Delete operation for invalid employee(RestCRUD.feature:49)
]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- com.runnerclass.TestRunnerClass -->
